prod:
  prod00:
    type: mysql
    dsn: test:test123@tcp(127.0.0.1:3306)/information_schema
  prod01:
    type: mysql
    dsn: test:test123@tcp(127.0.0.1:3306)/information_schema
  prod02:
    type: mysql
    dsn: test:test123@tcp(127.0.0.1:3306)/information_schema
  prod03:
    type: mysql
    dsn: test:test123@tcp(127.0.0.1:3306)/information_schema
  prod04:
    type: mysql
    dsn: test:test123@tcp(127.0.0.1:3306)/information_schema
  prod05:
    type: mysql
    dsn: test:test123@tcp(127.0.0.1:3306)/information_schema
dev:
  dev01:
    type: mysql
    dsn: test:test123@tcp(127.0.0.1:3306)/information_schema
postgres:
  pg01:
    type: postgres
    dsn: postgres://test:test12@localhost/postgres?sslmode=disable