prod:
  prod00:
    type: mysql
    dsn: tcp(127.0.0.1:3306)/information_schema
    user: test
    pass: test123
  prod01:
    type: mysql
    dsn: tcp(127.0.0.1:3306)/information_schema
    user: test
    pass: test123
  prod02:
    type: mysql
    dsn: tcp(127.0.0.1:3306)/information_schema
    user: test
    pass: test123
  prod03:
    type: mysql
    dsn: tcp(127.0.0.1:3306)/information_schema
    user: test
    pass: test123
  prod04:
    type: mysql
    dsn: tcp(127.0.0.1:3306)/information_schema
    user: test
    pass: test123
  prod05:
    type: mysql
    dsn: tcp(127.0.0.1:3306)/information_schema
    user: test
    pass: test123
dev:
  dev01:
    type: mysql
    dsn: tcp(127.0.0.1:3306)/information_schema
    user: test
    pass: test123