bind: 0.0.0.0:9104
type: mysql
dsn: test:test123@tcp(127.0.0.1:3306)/information_schema
instance: mytest
metrics:
  process_count_by_host:
    query: "select user, substring_index(host, ':', 1) host, count(*) sessions from information_schema.processlist group by 1,2 "
    type: guage
    description: "process count by host"
    labels: ["user","host"]
    value: sessions
  process_count_by_user:
    query: "select user, count(*) sessions from information_schema.processlist group by 1 "
    type: guage
    description: "process count by user"
    labels: ["user"]
    value: sessions